version: "3"
services:
  chatgpt-nux:
    image: node:latest
    ports:
      - 80:3000
    working_dir: /app # 指定容器内的工作目录 (Specify the working target in the container)
    volumes:
      - .output/:/app # 把当前宿主机的目录映射到容器内 (Map the directory of the current host to the container)
    command: node server/index.mjs
    restart: unless-stopped # 自动重启
